Pvw 7 landing image
PERMIKA-Vancouver/PERMIKA_Vancouver pull request #2
Opened 2023-08-01 23:22 UTC by filipomarcellino

2023-08-24 04:27 UTC, Julian-UBC requested changes

2023-08-24 04:27 UTC, Julian-UBC commented on client/src/App.css
> -/* RegoReg60 */
Can you keep this comment there

2023-08-24 04:27 UTC, Julian-UBC commented on client/src/App.css
> -/* RegoReg48 */
This one too

2023-08-24 04:27 UTC, Julian-UBC commented on client/src/App.css
> -/* RegoReg30 */
This one too

2023-08-24 04:27 UTC, Julian-UBC commented on client/src/App.css
> +.App-logo {
can u remove unnecessary css

2023-08-24 04:27 UTC, Julian-UBC commented on client/src/pages/home/Home.tsx
Can you move your landing image to a component in the home

2023-08-24 16:40 UTC, filipomarcellino commented on client/src/App.css
> +.App-logo {
is the .app-logo not used?

2023-08-24 16:40 UTC, filipomarcellino commented on client/src/App.css
> -/* RegoReg48 */
added

2023-08-24 17:04 UTC, Julian-UBC commented on client/src/App.css
> +.App-logo {
Is it used by your landing image? If not, then it is not used

2023-08-24 17:19 UTC, Julian-UBC requested changes
Can you change `z-10` to `z-20` on line 41 in NavigationBar.tsx

2023-08-30 04:17 UTC, Julian-UBC requested changes

2023-08-30 04:17 UTC, Julian-UBC commented on client/src/shared/components/LandingImage.tsx
Can you move this component to pages/home/components

2023-08-30 04:17 UTC, Julian-UBC commented on client/src/shared/components/LandingImage.tsx
> +import React from "react";
you can remove this line 
```suggestion
```

2023-08-30 04:17 UTC, Julian-UBC commented on client/src/shared/components/LandingImage.tsx
> +  const [isVisible, setIsVisible] = useState(false);
what is this state for?

2023-09-20 22:19 UTC, filipomarcellino commented on client/src/shared/components/LandingImage.tsx
> +  const [isVisible, setIsVisible] = useState(false);
it's for the fading effect on images and header

2023-09-20 22:21 UTC, filipomarcellino commented on client/src/shared/components/LandingImage.tsx
done

2023-09-20 22:21 UTC, filipomarcellino commented on client/src/shared/components/LandingImage.tsx
> +import React from "react";
done

2023-09-20 23:25 UTC, Julian-UBC requested changes

2023-09-20 23:25 UTC, Julian-UBC commented on client/src/App.css
> +/* RegoReg60 */
I think you accidentally decline upcoming changes here

2023-10-01 05:05 UTC, Julian-UBC approved these changes
Great work!!!

2023-10-01 06:33 UTC, Julian-UBC requested changes

2023-10-01 06:33 UTC, Julian-UBC commented on client/src/pages/home/components/LandingImageSmall.tsx
> +                <p className="z-20 text-md mdVertical:text-2xl text-left w-9/12 text-gray-500 pt-4 font-RegoReg">
```suggestion
                <p className="z-20 text-md mdVertical:text-2xl text-left w-9/12 text-[#9A9A9A] pt-4 font-RegoReg">
```

2023-10-01 22:12 UTC, mayaramadhina approved these changes

2023-10-02 00:10 UTC, Julian-UBC approved these changes
Great work @filipomarcellino!!!

2023-10-02 00:10 UTC, merged