Order page revamp
PERMIKA-Vancouver/PERMIKA_Vancouver pull request #72
Opened 2024-07-09 02:47 UTC by Soontobecoder

changed the layout of order page to show your cart on the left

2024-07-09 20:34 UTC, Julian-UBC requested changes

2024-07-09 20:34 UTC, Julian-UBC commented on client/src/pages/order/data/data.ts
> +    price: 35,
32

2024-07-09 20:34 UTC, Julian-UBC commented on client/src/pages/order/data/data.ts
> +    price: 35,
32

2024-07-09 20:34 UTC, Julian-UBC commented on client/src/pages/order/data/data.ts
> +    price: 20,
18

2024-07-09 22:07 UTC, Julian-UBC requested changes

2024-07-09 22:07 UTC, Julian-UBC commented on client/src/pages/order/Order.tsx
> +                            'https://forms.gle/wSxUEACu6ydqegVh9'
```suggestion
                            'https://forms.gle/RbuP9j3wqG5ZKAuaA'
```

2024-07-09 22:07 UTC, Julian-UBC commented on client/src/pages/order/Order.tsx
>                        setPaymentClicked(true);
```suggestion
                      setSubmitOrderClicked(true);
```

2024-07-09 22:07 UTC, Julian-UBC commented on client/src/pages/order/Order.tsx
>                        openExternalLink('https://forms.gle/RbuP9j3wqG5ZKAuaA');
```suggestion
                      handleNextPage();
```

2024-07-10 02:39 UTC, Julian-UBC approved these changes

2024-07-10 03:30 UTC, rliebig2004 approved these changes
looks good!

2024-07-10 03:51 UTC, merged