added panelists and delegates layout
PERMIKA-Vancouver/PERMIKA_Vancouver pull request #97
Opened 2024-10-29 23:38 UTC by Soontobecoder

2024-10-30 13:09 UTC, rliebig2004 approved these changes

2024-10-31 20:12 UTC, Julian-UBC requested changes

2024-10-31 20:12 UTC, Julian-UBC commented on client/src/pages/nextgen/components/Panelist.tsx
> +    <div className="min-h-[50vh] bg-forest-green py-36 lg:flex items-center justify-center pl-all lg:!pl-0">
<img width="1258" alt="Screenshot 2024-10-31 at 1 08 25 PM" src="https://github.com/user-attachments/assets/abf42396-587a-46d0-8902-1b4fd1f153ed">
Can you just stick to `pl-all` biar ga beda left padding/marginnya. Gpp ga usa centered horizontally

2024-10-31 20:12 UTC, Julian-UBC commented on client/src/pages/nextgen/components/Delegates.tsx
> +    <div className="min-h-[50vh] bg-forest-green py-36 lg:flex items-center justify-center pl-all lg:!pl-0">
Same thing here with panelists

2024-10-31 20:36 UTC, Julian-UBC approved these changes

2024-10-31 20:38 UTC, merged